### ISSUE TITLE
Menu Noodom - Pimp my Jeedom - Choix des types de menus

### ISSUE THREAD

**Issue by ducloslaurent** [noodom/jeedom_menus#2]
Bonjour Noodom,
Je viens d'installer Pimp My Jeedom en version Beta et d'installer un menu by Noodom.
Dans la liste des choix des menus, seuls 3 choix apparaissent : FSB33 / Animation / TomButton, tous les autres types de menus (Floatting Draggable, HoverShow, InTheAir...) ne sont pas dispo dans la liste déroumante de choix des menus.
La gestion des liens vers les designs directement dans "Designs liés et paramètres" est beaucoup plus simple directment via le choix des menus que de configurer les fichier JSon.
Superbe boulot!

**Comment by noodom** [comment]
Salut,

Merci de ton retour.

En effet, ce sont hélas les seuls menus actuellement disponibles sur le plugin Pimp My Jeedom.
Ceci est dû au fait qu'il faut les modifier pour les adapter au plugin, ce qui demande du temps de développement et de validation.
Mais c'est clair que le plugin simplifie énormément la construction de ces menus (génération du menu en quelques clics) et aussi la possibilté de modifier son contenu.
